import fs from 'node:fs';import vm from 'node:vm';
import test from 'node:test';import assert from 'node:assert/strict';import {renderToString} from 'react-dom/server';import {MemoryRouter} from 'react-router-dom';import Home from '../src/pages/Home';import Cart from '../src/pages/Cart';import {addToCart,getCart,updateQuantity,removeFromCart,getCartTotal} from '../src/lib/cart';
const data=new Map<string,string>();Object.defineProperty(globalThis,'sessionStorage',{configurable:true,value:{getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>data.set(k,v)}});globalThis.fetch=async()=>{throw Error('Network forbidden');};
test('historical Mirror Shop retains five original categories, card animations, images and add action',()=>{const html=renderToString(<MemoryRouter><Home/></MemoryRouter>);for(const text of ['Collezione Shop','Scarpe','Borse','Capispalla','Vestiti','Top','sneaker.png','bag.png','animate-fade-in','group-hover:scale-105','Aggiungi al carrello'])assert.ok(html.includes(text));assert.equal((html.match(/Aggiungi al carrello/g)??[]).length,5);});
test('historical generic cart quantities and removal remain independent from guest credentials',()=>{data.clear();data.set('drip-checkout-guest-v1:order_A','unchanged');addToCart({id:'shoes-test',name:'Calzature premium',description:'Synthetic',price:12000,quantity:1});assert.equal(getCartTotal(),12000);updateQuantity('shoes-test',2);assert.equal(getCartTotal(),24000);assert.equal(getCart()[0].quantity,2);removeFromCart('shoes-test');assert.equal(getCart().length,0);assert.equal(data.get('drip-checkout-guest-v1:order_A'),'unchanged');});
test('historical empty cart, layout and footer remain rendered without starting payment',()=>{const html=renderToString(<MemoryRouter><Cart/></MemoryRouter>);assert.ok(html.includes('Il tuo carrello'));assert.ok(html.includes('Il carrello'));assert.ok(html.includes('max-w-3xl'));assert.ok(html.includes('Protetto da'));});

test('Mirror final button executes real handler without network, order, payment, redirect or cart clearing',async()=>{const source=fs.readFileSync('src/pages/Cart.tsx','utf8'),handler=source.match(/const handleCheckout = async \(\) => \{([\s\S]*?)\n {2}\};/)![0];let effects=0;const ctx={cart:[{id:'shoes-test',quantity:1}],toast:()=>effects++,fetch:()=>{effects++;throw Error('network forbidden');},window:{location:{assign:()=>effects++}},console};vm.runInNewContext(handler+'; globalThis.run=handleCheckout;',ctx);await (ctx as typeof ctx & {run:()=>Promise<void>}).run();assert.equal(effects,0);assert.equal(ctx.cart.length,1);assert.ok(!source.includes('seamless/checkout'));});

test('all five historical image sources stay exact and local assets exist',()=>{const html=renderToString(<MemoryRouter><Home/></MemoryRouter>);for(const url of ['/sneaker.png','/bag.png','https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=300&fit=crop','https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=300&fit=crop','https://images.unsplash.com/photo-1562157873-818bc0726f68?w=400&h=300&fit=crop'])assert.ok(html.includes(url.replace(/&/g,'&amp;')));for(const file of ['public/sneaker.png','public/bag.png'])assert.ok(fs.statSync(file).size>0);});
