import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {loadNavigationOrder,readAttempt} from '../src/lib/secureCheckout';
const map=new Map<string,string>(),order='order_A',token='a'.repeat(43),ticket='t'.repeat(43);let calls:string[]=[];
function setup(){map.clear();calls=[];Object.defineProperty(globalThis,'sessionStorage',{configurable:true,value:{getItem:(k:string)=>map.get(k)||null,setItem:(k:string,v:string)=>map.set(k,v),removeItem:(k:string)=>map.delete(k)}});map.set('drip-navigation-v1:'+order,JSON.stringify({orderId:order,ticket}));globalThis.fetch=async(url,init)=>{const path=String(url);calls.push(path);assert.ok(!path.includes(token)&&!path.includes(ticket));if(path.endsWith('/redeem')){assert.equal(readAttempt(order).token,token);assert.equal(new Headers(init?.headers).get('Order-Access-Token'),token);assert.deepEqual(JSON.parse(init?.body as string),{orderId:order,ticket});return Response.json({orderId:order,authorized:true});}return Response.json(path.endsWith('/prepare')?{accessToken:token,expiresAt:new Date(Date.now()+60000).toISOString()}:{id:order,total:14.9,currency:'EUR',paymentStatus:'PENDING'});};}
test('navigation acquires own scoped grant once, removes temporary ticket after authorized read and reloads same grant',async()=>{setup();const result=await Promise.all([loadNavigationOrder(order),loadNavigationOrder(order)]);assert.equal(result[0].id,order);assert.equal(calls.length,3);assert.equal(readAttempt(order).authorized,true);assert.equal(map.has('drip-navigation-v1:'+order),false);await loadNavigationOrder(order);assert.equal(calls.length,4);assert.equal(readAttempt(order).token,token);});
test('orderId alone and ticket bound to another order block before mutation',async()=>{setup();await assert.rejects(loadNavigationOrder('order_B'));assert.equal(calls.length,0);map.set('drip-navigation-v1:'+order,JSON.stringify({orderId:'order_B',ticket}));await assert.rejects(loadNavigationOrder(order));assert.equal(calls.length,0);});
test('lost redemption response retains same recipient and ticket for retry',async()=>{setup();const ok=globalThis.fetch;let lost=true;globalThis.fetch=async(url,init)=>{if(String(url).endsWith('/redeem')&&lost){lost=false;throw new Error('synthetic lost response');}return ok(url,init);};await assert.rejects(loadNavigationOrder(order));assert.equal(readAttempt(order).token,token);assert.ok(map.has('drip-navigation-v1:'+order));await loadNavigationOrder(order);assert.equal(calls.filter(p=>p.endsWith('/prepare')).length,1);});
test('denied, expired, revoked ticket and wrong response never adopt authorized access',async()=>{for(const status of [401,410,409]){setup();map.set('drip-checkout-guest-v1:'+order,JSON.stringify({orderId:order,token,payCalls:0,prepareCalls:1}));globalThis.fetch=async()=>Response.json({error:'NAVIGATION_DENIED'},{status});await assert.rejects(loadNavigationOrder(order));assert.equal(readAttempt(order).authorized,undefined);}setup();globalThis.fetch=async()=>Response.json({orderId:'order_B',authorized:true});await assert.rejects(loadNavigationOrder(order));assert.equal(readAttempt(order).authorized,undefined);});
test('existing session/pairing conflicts and concurrent credential replacement never overwrite local state',async()=>{setup();map.set('drip-checkout-guest-v1:'+order,JSON.stringify({orderId:order,token,authorized:true,sessionId:'cs_existing',payCalls:2,prepareCalls:1}));await loadNavigationOrder(order);assert.equal(readAttempt(order).sessionId,'cs_existing');assert.equal(readAttempt(order).payCalls,2);setup();map.set('drip-checkout-guest-v1:'+order,JSON.stringify({orderId:order,token,payCalls:0,prepareCalls:1}));globalThis.fetch=async()=>{map.set('drip-checkout-guest-v1:'+order,JSON.stringify({orderId:order,token:'b'.repeat(43),payCalls:0,prepareCalls:1}));return Response.json({orderId:order,authorized:true});};await assert.rejects(loadNavigationOrder(order));assert.equal(readAttempt(order).token,'b'.repeat(43));});
test('early HTML bootstrap strips fragment before modules and refuses overwriting another association',()=>{const html=fs.readFileSync('index.html','utf8'),script=html.match(/<script>([\s\S]*?)<\/script>/)![1];assert.ok(html.indexOf('<script>')<html.indexOf('type="module"'));let replaced='';const ctx={location:{hash:'#navigation='+ticket,search:'?orderId='+order,pathname:'/checkout-landing'},URLSearchParams,history:{state:null,replaceState:(_s:unknown,_t:string,url:string)=>{replaced=url;}},sessionStorage:{getItem:()=>null,setItem:(key:string,value:string)=>{assert.equal(replaced,'/checkout-landing?orderId='+order);assert.ok(!value.includes(token));}}};vm.runInNewContext(script,ctx);assert.ok(!replaced.includes(ticket));});
