import {test,beforeEach} from "node:test";
import assert from "node:assert/strict";
import {preparePairing,checkPairing,readAttempt,readOrder,pay,confirm,formatMoney,errorMessage,renewPendingPairing,CheckoutError} from "@/lib/secureCheckout";
let data:Map<string,string>,requests:{path:string;init:RequestInit}[];
const order="synthetic-a",token="C".repeat(43),id="P".repeat(32);
const pending={pairingId:id,orderId:order,phrase:"abcd-1234-5678",expiresAt:new Date(Date.now()+300000).toISOString(),state:"pending"};
beforeEach(()=>{data=new Map();requests=[];globalThis.sessionStorage={getItem:k=>data.get(k)??null,setItem:(k,v)=>{data.set(k,v);},removeItem:k=>{data.delete(k);},clear:()=>data.clear(),key:i=>[...data.keys()][i]??null,get length(){return data.size;}};globalThis.fetch=async(url,init={})=>{const path=new URL(String(url)).pathname;requests.push({path,init});if(path.endsWith("/prepare"))return Response.json({accessToken:token,expiresAt:new Date(Date.now()+900000).toISOString()});if(path.endsWith("/order-handoffs"))return Response.json(pending);if(path.endsWith("/redeem"))return Response.json({...pending,state:"approved"});if(path.endsWith("/min"))return Response.json({id:order,total:99.9,currency:"EUR",paymentStatus:"PAID",status:"PROCESSING"});if(path.endsWith("/pay"))return Response.json({url:"https://checkout.stripe.com/c/pay/synthetic",sessionId:"cs_test_synthetic"});if(path.endsWith("/confirm"))return Response.json({paid:true,order:{id:order}});throw new Error("UNMOCKED");};});
async function authorized(){await preparePairing(order);await checkPairing(order);}
test("preparation persists recipient token before pairing request; no secret in URL, cache, body or diagnostics",async()=>{await preparePairing(order);assert.equal(readAttempt(order).token,token);const r=requests[1];assert.equal((r.init.headers as Record<string,string>)["Order-Access-Token"],token);assert.ok(!String(r.init.body).includes(token));assert.equal(r.init.cache,"no-store");assert.equal(r.init.referrerPolicy,"no-referrer");assert.ok(requests.every(r=>!r.path.includes(token)));});
test("parallel prepare calls and reload reuse same pairing and credential",async()=>{const [a,b]=await Promise.all([preparePairing(order),preparePairing(order)]);assert.deepEqual(a,b);const n=requests.length;assert.deepEqual(await preparePairing(order),a);assert.equal(requests.length,n);});
test("lost pairing response retries with same prepared token without preparing another secret",async()=>{const normal=fetch;let lost=true;globalThis.fetch=async(url,init)=>{if(String(url).endsWith("/order-handoffs")&&lost){lost=false;throw new TypeError("offline");}return normal(url,init);};await assert.rejects(preparePairing(order));assert.equal(readAttempt(order).token,token);await preparePairing(order);assert.equal(requests.filter(r=>r.path.endsWith("/prepare")).length,1);});
test("recipient is unauthorized before approval; repeated approval checks persist same scoped grant",async()=>{await preparePairing(order);await assert.rejects(readOrder(order));await checkPairing(order);await checkPairing(order);assert.equal((await readOrder(order)).id,order);assert.equal(readAttempt(order).token,token);});
test("forged pairing response for another order cannot grant access",async()=>{await preparePairing(order);globalThis.fetch=async()=>Response.json({...pending,orderId:"synthetic-b",state:"approved"});await assert.rejects(checkPairing(order));assert.ok(!readAttempt(order).authorized);});
test("malformed or conflicting phrase cannot authorize recipient",async()=>{await preparePairing(order);globalThis.fetch=async()=>Response.json({...pending,phrase:"ffff-ffff-ffff",state:"approved"});await assert.rejects(checkPairing(order));});
test("credential for order A never authorizes B or fallback anonymous calls",async()=>{await authorized();const count=requests.length;await assert.rejects(readOrder("synthetic-b"));assert.equal(requests.length,count);});
test("storage blocked prevents every network preparation and payment",async()=>{sessionStorage.setItem=()=>{throw new Error("blocked");};await assert.rejects(preparePairing(order));assert.equal(requests.length,0);});
test("payment response lost: retry uses same order and persists one known session before navigation",async()=>{await authorized();const normal=fetch;let lost=true;globalThis.fetch=async(url,init)=>{if(String(url).endsWith("/pay")&&lost){lost=false;throw new TypeError("lost response");}return normal(url,init);};await assert.rejects(pay(order));const p=await pay(order);assert.equal(readAttempt(order).sessionId,p.sessionId);assert.equal(readAttempt(order).payCalls,2);assert.equal(JSON.parse(String(requests.at(-1)!.init.body)).orderId,order);});
test("concurrent payment clicks are deduplicated",async()=>{await authorized();await Promise.all([pay(order),pay(order)]);assert.equal(requests.filter(r=>r.path.endsWith("/pay")).length,1);});
test("known session is never silently replaced; payment URL must be Stripe HTTPS",async()=>{await authorized();await pay(order);globalThis.fetch=async()=>Response.json({url:"https://checkout.stripe.com/c/pay/other",sessionId:"cs_other"});await assert.rejects(pay(order));assert.equal(readAttempt(order).sessionId,"cs_test_synthetic");globalThis.fetch=async()=>Response.json({url:"https://evil.example.invalid",sessionId:"cs_test_synthetic"});await assert.rejects(pay(order));});
test("Stripe return validates persisted session and exact order before confirmation",async()=>{await authorized();await pay(order);await assert.rejects(confirm(order,"cs_forged"));assert.equal((await confirm(order,"cs_test_synthetic")).paid,true);const normal=fetch;globalThis.fetch=async(url,init)=>String(url).includes("/confirm?")?Response.json({paid:true,order:{id:"other"}}):normal(url,init);await assert.rejects(confirm(order,"cs_test_synthetic"));});
test("stored session survives interrupted navigation, reconstructed state and same-tab return",async()=>{await authorized();await pay(order);assert.equal(readAttempt(order).sessionId,"cs_test_synthetic");assert.equal((await confirm(order,readAttempt(order).sessionId!)).paid,true);});
test("429 enforces persisted cooldown with no extra request; error bodies never exposed",async()=>{await authorized();globalThis.fetch=async()=>Response.json({error:"SECRET raw token "+token},{status:429,headers:{"Retry-After":"120"}});await assert.rejects(readOrder(order),e=>e instanceof CheckoutError&&e.status===429&&!e.message.includes(token));assert.ok(readAttempt(order).nextRequestAt!>Date.now()+100000);globalThis.fetch=async()=>{throw new Error("MUST_NOT_CALL");};await assert.rejects(readOrder(order),e=>e instanceof CheckoutError&&e.status===429);});
test("401 409 410 503 remain explicit and never rotate token or create order",async()=>{await authorized();for(const status of [401,409,410,503]){globalThis.fetch=async()=>Response.json({error:"ORDER_ACCESS_DENIED"},{status});await assert.rejects(readOrder(order),e=>e instanceof CheckoutError&&e.status===status);assert.equal(readAttempt(order).token,token);}assert.ok(errorMessage(new CheckoutError(401,"DENIED")).includes("assistenza"));});
test("order monetary values are EUR units, not cents or USD",()=>{assert.match(formatMoney(9.9),/9,90/);assert.match(formatMoney(99.9),/99,90/);assert.throws(()=>formatMoney(99.9,"USD"));assert.throws(()=>formatMoney(NaN));});
test("a pending expired pairing can be renewed explicitly without resetting order or payment budget",async()=>{await preparePairing(order);const a=readAttempt(order);a.pairing!.expiresAt=new Date(0).toISOString();data.set("drip-checkout-guest-v1:"+order,JSON.stringify(a));globalThis.fetch=async()=>Response.json({error:"HANDOFF_EXPIRED"},{status:410});await renewPendingPairing(order);assert.equal(readAttempt(order).orderId,order);assert.equal(readAttempt(order).token,undefined);assert.equal(readAttempt(order).prepareCalls,1);});
test("expired pending renew is forbidden for a known authorized session",async()=>{await authorized();await pay(order);await assert.rejects(renewPendingPairing(order));});
test("reads can be cancelled during rapid navigation without replacing another order",async()=>{await authorized();globalThis.fetch=async(_url,init)=>new Promise<Response>((_resolve,reject)=>{init!.signal!.addEventListener("abort",()=>reject(new DOMException("Aborted","AbortError")));});const c=new AbortController(),p=readOrder(order,c.signal);c.abort();await assert.rejects(p);assert.equal(readAttempt(order).orderId,order);});

test("deadline also aborts a stalled response body without resetting the attempt",async()=>{await authorized();globalThis.fetch=async(_url,init)=>({ok:true,json:()=>new Promise((_resolve,reject)=>init.signal.addEventListener("abort",()=>reject(new DOMException("Timeout","AbortError"))))} as unknown as Response);await assert.rejects(readOrder(order));assert.equal(readAttempt(order).token,token);});

test("lost approval does not permit local expiry to rotate a still-valid authorized credential",async()=>{await preparePairing(order);const a=readAttempt(order);a.pairing!.expiresAt=new Date(0).toISOString();data.set("drip-checkout-guest-v1:"+order,JSON.stringify(a));assert.equal(await renewPendingPairing(order),false);assert.equal(readAttempt(order).token,token);assert.equal(readAttempt(order).authorized,true);});
test("network uncertainty during expiry verification preserves prepared credential and pairing",async()=>{await preparePairing(order);const a=readAttempt(order);a.pairing!.expiresAt=new Date(0).toISOString();data.set("drip-checkout-guest-v1:"+order,JSON.stringify(a));globalThis.fetch=async()=>{throw new TypeError("offline");};await assert.rejects(renewPendingPairing(order));assert.equal(readAttempt(order).token,token);assert.equal(readAttempt(order).pairing!.pairingId,id);});

test("late rate-limit response cannot erase a session saved by a concurrent operation",async()=>{
 await authorized();const normal=fetch;let complete!:(r:Response)=>void;
 globalThis.fetch=async(url,init)=>String(url).endsWith("/min")?new Promise<Response>(r=>{complete=r;}):normal(url,init);
 const read=readOrder(order);await pay(order);
 const rejection=assert.rejects(read,e=>e instanceof CheckoutError&&e.status===429);
 complete(Response.json({error:"RATE_LIMIT"},{status:429,headers:{"Retry-After":"60"}}));await rejection;
 assert.equal(readAttempt(order).sessionId,"cs_test_synthetic");assert.equal(readAttempt(order).token,token);
});
