const {test,before,after}=require('node:test');
const assert=require('node:assert/strict'),{createHash,randomUUID}=require('node:crypto'),{PrismaClient}=require('@prisma/client');
const db=new PrismaClient(),hash=t=>createHash('sha256').update(t).digest('hex');
process.env.NAVIGATION_HANDOFF_SECRET='synthetic-navigation-secret-for-local-only';
let calls=0,request;const sessions=new Map();class FakeStripe{constructor(){this.checkout={sessions:{create:async p=>{calls++;request=p;const s={id:'cs_navigation_'+calls,url:'https://checkout.stripe.com/c/pay/synthetic',mode:'payment',status:'open',payment_status:'unpaid',metadata:p.metadata,amount_total:p.line_items[0].price_data.unit_amount,currency:p.line_items[0].price_data.currency};sessions.set(s.id,s);return s;},retrieve:async id=>sessions.get(id)}};}}
require.cache[require.resolve('stripe')]={exports:FakeStripe};
const {createApp}=require('../dist/app'),shared=require('../dist/prisma').default;
const {createNavigation,redeemNavigation}=require('../dist/services/navigationHandoff');
const origins={store:'https://store.example.invalid',checkout:'https://checkout.example.invalid'};let server,base;
async function restart(){if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}server=createApp({logging:false,staging:true,orderAccessRequired:true,handoffOrigins:origins}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port+'/api';}
before(async()=>{assert.equal(new URL(process.env.DATABASE_URL).hostname,'127.0.0.1');await restart();});
after(async()=>{await db.navigationHandoff.deleteMany();server.closeAllConnections();await new Promise(r=>server.close(r));await db.$disconnect();await shared.$disconnect();});
async function req(path,token,body={},origin=origins.checkout,key){const r=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json',...(origin?{Origin:origin}:{}),...(token?{'Order-Access-Token':token}:{}),...(key?{'Idempotency-Key':key}:{})},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};}
async function prepare(){const r=await req('/order-access/prepare');assert.equal(r.status,201);return r.body.accessToken;}
async function fixture(){const source=await prepare(),recipient=await prepare(),order=await db.order.create({data:{customerName:'Navigation Synthetic',customerEmail:'navigation@example.invalid',total:'20.90'}});await db.guestOrderAccess.update({where:{tokenHash:hash(source)},data:{orderId:order.id}});return {source,recipient,id:order.id};}
const create=(f,key=randomUUID())=>req('/orders/'+f.id+'/navigation-handoffs',f.source,{},origins.store,key);
const redeem=(f,ticket,token=f.recipient,origin=origins.checkout)=>req('/navigation-handoffs/redeem',token,{orderId:f.id,ticket},origin);
test('navigation creation concurrent/idempotent survives process restart and stores no raw ticket',async()=>{const f=await fixture(),key=randomUUID(),rs=await Promise.all([create(f,key),create(f,key)]);assert.equal(rs[0].status,200);assert.equal(rs[0].body.ticket,rs[1].body.ticket);await restart();assert.equal((await create(f,key)).body.ticket,rs[0].body.ticket);assert.ok(!JSON.stringify(await db.navigationHandoff.findMany()).includes(rs[0].body.ticket));});
test('exact origin, source/order and creation key are required; no anonymous access',async()=>{const f=await fixture();for(const origin of [null,'null',origins.checkout,origins.store+'.evil'])assert.equal((await req('/orders/'+f.id+'/navigation-handoffs',f.source,{},origin,randomUUID())).status,403);assert.equal((await req('/orders/'+f.id+'/navigation-handoffs',null,{},origins.store,randomUUID())).status,401);const g=await fixture();assert.equal((await req('/orders/'+f.id+'/navigation-handoffs',g.source,{},origins.store,randomUUID())).status,401);assert.equal((await create(f,'short')).status,400);});
test('concurrent redemption and lost response bind once; same recipient reload after ticket expiry succeeds',async()=>{const f=await fixture(),p=await create(f),ticket=p.body.ticket,rs=await Promise.all([redeem(f,ticket),redeem(f,ticket)]);assert.ok(rs.every(r=>r.status===200));const g=await db.guestOrderAccess.findUniqueOrThrow({where:{tokenHash:hash(f.recipient)}});await db.navigationHandoff.update({where:{ticketHash:hash(ticket)},data:{expiresAt:new Date(0)}});await restart();assert.equal((await redeem(f,ticket)).status,200);assert.equal((await db.guestOrderAccess.findUniqueOrThrow({where:{tokenHash:hash(f.recipient)}})).expiresAt.getTime(),g.expiresAt.getTime());assert.equal((await redeem(f,ticket,await prepare())).status,409);});
test('unknown ticket, wrong order/destination, absent and expired ticket are blocked',async()=>{const f=await fixture(),g=await fixture(),p=await create(f);assert.equal((await redeem(g,p.body.ticket)).status,401);assert.equal((await redeem(f,p.body.ticket,f.recipient,origins.store)).status,403);assert.equal((await redeem(f,'x'.repeat(43))).status,401);await db.navigationHandoff.update({where:{ticketHash:hash(p.body.ticket)},data:{expiresAt:new Date(0)}});assert.equal((await redeem(f,p.body.ticket)).status,410);assert.equal((await db.guestOrderAccess.findUniqueOrThrow({where:{tokenHash:hash(f.recipient)}})).orderId,null);});
test('revocation, expired recipient and source token cannot bind a new recipient',async()=>{const f=await fixture(),p=await create(f);assert.equal((await redeem(f,p.body.ticket,f.source)).status,401);await db.guestOrderAccess.update({where:{tokenHash:hash(f.recipient)},data:{expiresAt:new Date(0)}});assert.equal((await redeem(f,p.body.ticket)).status,401);const {revokeGuestAccess}=require('../dist/services/guestOrderAccess');await revokeGuestAccess(f.id);assert.equal((await redeem(f,p.body.ticket,await prepare())).status,401);assert.ok((await db.navigationHandoff.findUniqueOrThrow({where:{ticketHash:hash(p.body.ticket)}})).revokedAt);});
test('verified recovery revokes pending navigation tickets',async()=>{const f=await fixture(),p=await create(f),{requestGuestRecovery,redeemGuestRecovery}=require('../dist/services/guestOrderAccess');let delivered;await requestGuestRecovery(f.id,'navigation@example.invalid',async m=>{delivered=m;});await redeemGuestRecovery(delivered.recoveryToken);assert.equal((await redeem(f,p.body.ticket)).status,401);});
test('binding transaction rollback preserves prepared recipient and retry',async()=>{const f=await fixture(),p=await create(f);await db.$executeRawUnsafe(`CREATE FUNCTION synthetic_navigation_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic failure'; END $$`);await db.$executeRawUnsafe('CREATE TRIGGER synthetic_navigation_failure BEFORE UPDATE ON "NavigationHandoff" FOR EACH ROW EXECUTE FUNCTION synthetic_navigation_failure()');try{await assert.rejects(redeemNavigation(f.id,p.body.ticket,f.recipient,origins.checkout));assert.equal((await db.guestOrderAccess.findUniqueOrThrow({where:{tokenHash:hash(f.recipient)}})).orderId,null);}finally{await db.$executeRawUnsafe('DROP TRIGGER synthetic_navigation_failure ON "NavigationHandoff"');await db.$executeRawUnsafe('DROP FUNCTION synthetic_navigation_failure()');}assert.equal((await redeemNavigation(f.id,p.body.ticket,f.recipient,origins.checkout)).authorized,true);});
test('quota bounds ticket creation; replay does not create additional rows',async()=>{const f=await fixture();for(let i=0;i<10;i++)await createNavigation(f.id,f.source,randomUUID(),origins.checkout);await assert.rejects(createNavigation(f.id,f.source,randomUUID(),origins.checkout),e=>e.status===429);assert.equal(await db.navigationHandoff.count({where:{orderId:f.id}}),10);});
test('server shipping threshold before discount, spoofed amounts ignored, immutable order replay',async()=>{
 for(const [price,expected] of [['11.00',16],['199.99',204.99],['200.00',200],['250.00',250]]){const token=await prepare(),product=await db.product.create({data:{handle:'nav-shipping-'+price,title:'Synthetic shipping',variants:{create:{price,inventoryQuantity:4}}}}),key=randomUUID(),body={customerName:'Synthetic',customerEmail:'shipping@example.invalid',items:[{productId:product.id,quantity:1}],shippingAmount:0,total:0};const r=await req('/checkout/intent',token,body,origins.store,key);assert.equal(r.status,201);const o=await db.order.findUniqueOrThrow({where:{id:r.body.orderId}});assert.equal(Number(o.total),expected);assert.equal((await req('/checkout/intent',token,body,origins.store,key)).body.orderId,o.id);}
});
test('shipping after discount is included in aggregate Stripe total and finalizes stock/discount once',async()=>{
 const source=await prepare(),recipient=await prepare(),product=await db.product.create({data:{handle:'nav-paid-discount',title:'PRIVATE PRODUCT',variants:{create:{price:'11.00',sku:'PRIVATE SKU',inventoryQuantity:4}}}});await db.discount.create({data:{code:'NAV10',type:'PERCENTAGE',value:'10',active:true,usageLimit:4}});
 const r=await req('/checkout/intent',source,{customerName:'Synthetic',customerEmail:'payment@example.invalid',items:[{productId:product.id,quantity:1}],discountCode:'NAV10'},origins.store,randomUUID());assert.equal(r.status,201);const f={id:r.body.orderId,source,recipient},p=await create(f);await redeem(f,p.body.ticket);
 const rs=await Promise.all([req('/pay',recipient,{orderId:f.id}),req('/pay',recipient,{orderId:f.id})]);assert.ok(rs.every(r=>r.status===200));assert.equal(rs[0].body.sessionId,rs[1].body.sessionId);assert.equal(calls,1);assert.equal(request.line_items.length,1);assert.equal(request.line_items[0].price_data.unit_amount,1490);assert.equal(request.line_items[0].price_data.currency,'eur');assert.ok(!JSON.stringify(request).includes('PRIVATE'));
 const session=sessions.get(rs[0].body.sessionId);session.payment_status='paid';session.status='complete';for(let i=0;i<2;i++){const res=await fetch(base+'/pay/confirm?session_id='+session.id,{headers:{'Order-Access-Token':recipient,Origin:origins.checkout}});assert.equal(res.status,200);assert.equal((await res.json()).paid,true);}assert.equal(await db.paymentFinalization.count({where:{orderId:f.id}}),1);assert.equal((await db.discount.findUniqueOrThrow({where:{code:'NAV10'}})).usageCount,1);assert.equal((await db.variant.findFirstOrThrow({where:{productId:product.id}})).inventoryQuantity,3);
});

test('historical idempotent response preserves original total despite later staging fee policy',async()=>{const source=await prepare(),product=await db.product.create({data:{handle:'nav-old-fee-snapshot',title:'Synthetic legacy',variants:{create:{price:'11.00',inventoryQuantity:4}}}}),body={customerName:'Synthetic',customerEmail:'old@example.invalid',items:[{productId:product.id,quantity:1}]},key=randomUUID(),{createIdempotentOrder}=require('../dist/services/orderIdempotency');const historical=await createIdempotentOrder(body,'intent',key,source,false);assert.equal(historical.status,201);const before=await db.order.findUniqueOrThrow({where:{id:historical.response.orderId}});assert.equal(Number(before.total),11);const replay=await req('/checkout/intent',source,body,origins.store,key);assert.equal(replay.status,201);assert.equal(replay.body.orderId,before.id);assert.equal(Number((await db.order.findUniqueOrThrow({where:{id:before.id}})).total),11);});
test('free shipping threshold is merchandise subtotal before discount',async()=>{await db.discount.create({data:{code:'NAV-FREE10',type:'PERCENTAGE',value:'10',active:true,usageLimit:2}});const source=await prepare(),product=await db.product.create({data:{handle:'nav-free-discount',title:'Synthetic threshold',variants:{create:{price:'200.00',inventoryQuantity:2}}}});const r=await req('/checkout/intent',source,{customerName:'Synthetic',customerEmail:'free@example.invalid',items:[{productId:product.id,quantity:1}],discountCode:'NAV-FREE10'},origins.store,randomUUID());assert.equal(r.status,201);const order=await db.order.findUniqueOrThrow({where:{id:r.body.orderId}});assert.equal(Number(order.originalTotal),200);assert.equal(Number(order.discountAmount),20);assert.equal(Number(order.total),180);});

test('zero merchandise subtotal has five euro shipping, without allowing empty orders',()=>{const {shippingAmount}=require('../dist/services/shipping'),{Prisma}=require('@prisma/client');assert.equal(shippingAmount(new Prisma.Decimal(0),true).toFixed(2),'5.00');assert.equal(shippingAmount(new Prisma.Decimal(0),false).toFixed(2),'0.00');});
