const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {runtimeConfiguration}=require('../dist/runtimeConfiguration');
const good={DEPLOYMENT_ENV:'staging',PORT:'10000',DATABASE_URL:'postgresql://synthetic:synthetic@stage.example.invalid/magiccity_db_staging',STAGING_DATABASE_HOST:'stage.example.invalid',STRIPE_SECRET_KEY:'sk_test_synthetic',STRIPE_WEBHOOK_SECRET:'whsec_synthetic',JWT_SECRET:'synthetic-'.repeat(5),STAGING_STORE_ORIGIN:'https://store.stage.example.invalid',STAGING_CHECKOUT_ORIGIN:'https://store.stage.example.invalid',STAGING_API_ORIGIN:'https://api.stage.example.invalid',CHECKOUT_APP_URL:'https://store.stage.example.invalid/checkout',STRIPE_SUCCESS_URL:'https://store.stage.example.invalid/checkout/order-confirmation?orderId={ORDER_ID}&session_id={CHECKOUT_SESSION_ID}',STRIPE_CANCEL_URL:'https://store.stage.example.invalid/checkout/checkout-landing?orderId={ORDER_ID}'};
test('staging explicit configuration is valid; legacy defaults remain unchanged',()=>{assert.equal(runtimeConfiguration(good).port,10000);assert.equal(runtimeConfiguration({}).staging,false);});
test('staging fails closed on missing values without echoing secrets',()=>{for(const key of Object.keys(good).filter(k=>!['DEPLOYMENT_ENV','PORT'].includes(k))){const env={...good};delete env[key];assert.throws(()=>runtimeConfiguration(env));}});
test('production database names and wrong hosts are rejected',()=>{for(const database of ['postgresql://synthetic@stage.example.invalid/magiccitydb_3334','postgresql://synthetic@production.example.invalid/magiccity_db_staging'])assert.throws(()=>runtimeConfiguration({...good,DATABASE_URL:database}));});
test('live Stripe and weak JWT are refused',()=>{for(const patch of [{STRIPE_SECRET_KEY:'sk_live_never_use'},{JWT_SECRET:'short'},{STRIPE_API_VERSION:'2020-01-01'}])assert.throws(()=>runtimeConfiguration({...good,...patch}));});
test('public production origins, HTTP and credential-bearing return URLs are refused',()=>{for(const patch of [{STAGING_STORE_ORIGIN:'https://magiccitydrip.shop'},{STAGING_CHECKOUT_ORIGIN:'http://checkout.example.invalid'},{STRIPE_SUCCESS_URL:'https://user:pass@store.stage.example.invalid/checkout/order-confirmation'},{STRIPE_CANCEL_URL:'https://dripcheckout.netlify.app/cancel'},{STRIPE_CANCEL_URL:'https://store.stage.example.invalid/?token=secret'}])assert.throws(()=>runtimeConfiguration({...good,...patch}));});
test('invalid Render port and deployment mode are refused',()=>{for(const env of [{PORT:'NaN'},{PORT:'0'},{PORT:'65536'},{DEPLOYMENT_ENV:'stagign'}])assert.throws(()=>runtimeConfiguration(env));});
test('health, strict CORS, anonymous private access and webhook livemode use no database',async()=>{
 const {createApp}=require('../dist/app'),Stripe=require('stripe');
 const app=createApp({logging:false,staging:true,orderAccessRequired:true,allowedOrigins:['https://store.stage.example.invalid'],handoffOrigins:{store:'https://store.stage.example.invalid',checkout:'https://checkout.stage.example.invalid'}});
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const url='http://127.0.0.1:'+server.address().port;
 try{
 assert.equal((await fetch(url+'/healthz')).status,200);
 for(const origin of ['null','https://magiccitydrip.shop','https://store.stage.example.invalid.evil'])assert.equal((await fetch(url+'/healthz',{headers:{Origin:origin}})).status,403);
 const options=await fetch(url+'/api/pay',{method:'OPTIONS',headers:{Origin:'https://store.stage.example.invalid','Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'Order-Access-Token,Idempotency-Key'}});assert.equal(options.status,204);assert.equal(options.headers.get('access-control-allow-origin'),'https://store.stage.example.invalid');
 assert.equal((await fetch(url+'/api/orders/synthetic/min')).status,401);assert.equal((await fetch(url+'/api/admin/orders')).status,401);
 const signer=new Stripe('sk_test_synthetic');for(const live of [true,false]){const payload=JSON.stringify({id:'evt_synthetic',type:'synthetic.ignored',livemode:live,data:{object:{}}}),sig=signer.webhooks.generateTestHeaderString({payload,secret:process.env.STRIPE_WEBHOOK_SECRET});const r=await fetch(url+'/api/stripe/webhook',{method:'POST',headers:{'Content-Type':'application/json','Stripe-Signature':sig},body:payload});assert.equal(r.status,live?400:200);}
 }finally{server.closeAllConnections();await new Promise(r=>server.close(r));}
});
test('staging Stripe wrapper blocks copied recipients and live sessions before effects',async()=>{
 let calls=0,live=false;class FakeStripe{constructor(){this.checkout={sessions:{create:async()=>{calls++;return {id:'cs_test',livemode:false};},retrieve:async()=>({livemode:live})}};}}
 const context={exports:{},require:()=>FakeStripe,process:{env:{DEPLOYMENT_ENV:'staging',STRIPE_SECRET_KEY:'sk_test_synthetic'}}};vm.runInNewContext(fs.readFileSync(require.resolve('../dist/services/stripeClient'),'utf8'),context);const sessions=context.exports.stripe.checkout.sessions;
 for(const params of [{customer_email:'synthetic@example.invalid'},{customer:'cus_copied'},{payment_intent_data:{receipt_email:'synthetic@example.invalid'}}])assert.throws(()=>sessions.create(params));assert.equal(calls,0);await sessions.create({mode:'payment'});assert.equal(calls,1);live=true;await assert.rejects(sessions.retrieve('cs_test'));
});
