import test from 'node:test';import assert from 'node:assert/strict';import {AutomaticHandoff} from '@/lib/automaticHandoff';
const token='a'.repeat(43);let listener:(e:MessageEvent)=>void;const messages:Record<string,unknown>[]=[];let calls=0;const recipient={closed:false,location:{href:''},postMessage:(m:Record<string,unknown>,origin:string)=>{assert.equal(origin,'https://dripcheckout.netlify.app');messages.push(m);},close(){this.closed=true;}};
function setup(){calls=0;messages.length=0;recipient.closed=false;Object.defineProperty(globalThis,'window',{configurable:true,value:{open:()=>recipient,addEventListener:(_n:string,f:typeof listener)=>{listener=f;},removeEventListener:()=>{}}});Object.defineProperty(globalThis,'sessionStorage',{configurable:true,value:{getItem:()=>JSON.stringify({version:1,key:'a'.repeat(16),body:{items:[]},calls:0,state:'success',token,result:{orderId:'order_A'}})}});globalThis.fetch=async url=>{calls++;return new Response(JSON.stringify({orderId:'order_A',pairingId:'b'.repeat(32),phrase:'aaaa-bbbb-cccc',state:String(url).endsWith('/approve')?'approved':'pending'}),{status:200,headers:{'Content-Type':'application/json'}});};}
test('automatic handoff validates window, origin, order and nonces before approval; no token in messages',async()=>{setup();const flow=new AutomaticHandoff(),done=flow.start('order_A'),nonce=messages[0].nonce;const data={version:1,type:'pairing',orderId:'order_A',nonce,recipientNonce:'c'.repeat(16),pairingId:'b'.repeat(32),phrase:'aaaa-bbbb-cccc'};const send=(origin:string,source:unknown,extra={})=>listener({origin,source,data:{...data,...extra}} as MessageEvent);
 send('https://dripcheckout.netlify.app.evil.invalid',recipient);send('null',recipient);send('https://dripcheckout.netlify.app',{});send('https://dripcheckout.netlify.app',recipient,{orderId:'order_B'});send('https://dripcheckout.netlify.app',recipient,{nonce:'wrong'});send('https://dripcheckout.netlify.app',recipient,{type:'ready'});assert.equal(calls,0);
 send('https://dripcheckout.netlify.app',recipient);await new Promise(r=>setTimeout(r,10));assert.equal(calls,2);assert.equal(messages.at(-1)?.type,'approved');send('https://dripcheckout.netlify.app',recipient,{type:'ready'});await done;assert.equal(messages.at(-1)?.type,'done');assert.ok(!JSON.stringify(messages).includes(token));assert.ok(!recipient.location.href.includes(token));assert.ok(recipient.location.href.includes('orderId=order_A'));
});
test('blocked popup fails before any order or payment request',()=>{setup();Object.defineProperty(globalThis,'window',{configurable:true,value:{open:()=>null}});assert.throws(()=>new AutomaticHandoff());assert.equal(calls,0);});
test('cancelled transfer retains original association and creates no payment',async()=>{setup();const flow=new AutomaticHandoff();const done=flow.start('order_A');flow.cancel();await assert.rejects(done);assert.equal(calls,0);});
