import {readFileSync} from 'node:fs';import vm from 'node:vm';
import test from 'node:test';import assert from 'node:assert/strict';
import {navigateToCheckout,shippingEstimate} from '@/lib/navigationHandoff';import {rememberPaidCart,mayClearPaidCart,CART_REVISION} from '@/lib/paidCart';import type {CartItem} from '@/contexts/CartContext';
const order='order_A',token='a'.repeat(43),ticket='t'.repeat(43),map=new Map<string,string>(),local=new Map<string,string>();let calls=0;const destinations:string[]=[];
function setup(){calls=0;map.clear();local.clear();destinations.length=0;Object.defineProperty(globalThis,'sessionStorage',{configurable:true,value:{getItem:(k:string)=>map.get(k)||null,setItem:(k:string,v:string)=>map.set(k,v),removeItem:(k:string)=>map.delete(k)}});Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:(k:string)=>local.get(k)||null,setItem:(k:string,v:string)=>local.set(k,v)}});Object.defineProperty(globalThis,'window',{configurable:true,value:{location:{assign:(s:string)=>destinations.push(s)},open:()=>{throw new Error('popup forbidden');}}});map.set('magic-city-drip-checkout-pending',JSON.stringify({version:1,key:'a'.repeat(16),body:{items:[]},calls:1,state:'success',token,result:{orderId:order}}));globalThis.fetch=async(url,init)=>{calls++;assert.ok(!String(url).includes(token));assert.equal(new Headers(init?.headers).get('Order-Access-Token'),token);return Response.json({orderId:order,ticket,expiresAt:new Date(Date.now()+60000).toISOString()});};}
test('same-tab transfer deduplicates clicks, persists key and never puts durable token in URL',async()=>{setup();await Promise.all([navigateToCheckout(order),navigateToCheckout(order)]);assert.equal(calls,1);assert.equal(destinations.length,1);assert.equal(destinations[0],'https://checkout.example.invalid/checkout-landing?orderId=order_A#navigation='+ticket);assert.ok(!destinations[0].includes(token));const key=map.get('magic-city-navigation-v1:'+order);await navigateToCheckout(order);assert.equal(map.get('magic-city-navigation-v1:'+order),key);});
test('another order and a mismatched backend response never navigate',async()=>{setup();await assert.rejects(navigateToCheckout('order_B'));assert.equal(calls,0);globalThis.fetch=async()=>Response.json({orderId:'order_B',ticket,expiresAt:new Date(Date.now()+60000).toISOString()});await assert.rejects(navigateToCheckout(order));assert.equal(destinations.length,0);});
test('lost response retry preserves order, source token and navigation key',async()=>{setup();globalThis.fetch=async()=>{throw new Error('synthetic lost response');};await assert.rejects(navigateToCheckout(order));const key=map.get('magic-city-navigation-v1:'+order),raw=map.get('magic-city-drip-checkout-pending');globalThis.fetch=async()=>Response.json({orderId:order,ticket,expiresAt:new Date(Date.now()+60000).toISOString()});await navigateToCheckout(order);assert.equal(map.get('magic-city-navigation-v1:'+order),key);assert.equal(map.get('magic-city-drip-checkout-pending'),raw);});
test('shipping uses subtotal before discount and exact cents threshold',()=>{assert.equal(shippingEstimate(0),5);assert.equal(shippingEstimate(199.99),5);assert.equal(shippingEstimate(200),0);assert.equal(shippingEstimate(250),0);});
test('paid order clears only unchanged purchased cart; new lines, quantities, remove/re-add and missing snapshot remain',()=>{setup();const lines=[{product:{id:1},quantity:1,selectedSize:'M'}] as CartItem[];rememberPaidCart(order,lines,'initial');assert.equal(mayClearPaidCart(order,lines),true);assert.equal(mayClearPaidCart(order,[...lines,{product:{id:2},quantity:1}] as CartItem[]),false);assert.equal(mayClearPaidCart(order,[{...lines[0],quantity:2}]),false);local.set(CART_REVISION,'edited');assert.equal(mayClearPaidCart(order,lines),false);assert.equal(mayClearPaidCart('order_B',lines),false);});

test('cancelled Store navigation never redirects after a late successful response',async()=>{setup();let release:(r:Response)=>void;globalThis.fetch=async()=>new Promise<Response>(resolve=>{release=resolve;});const control=new AbortController(),pending=navigateToCheckout(order,control.signal);control.abort();release!(Response.json({orderId:order,ticket,expiresAt:new Date(Date.now()+60000).toISOString()}));await assert.rejects(pending);assert.equal(destinations.length,0);assert.ok(map.has('magic-city-drip-checkout-pending'));});

test('real Cart shipping display derives its amount from shared rule and keeps free label',()=>{const source=readFileSync('src/pages/Cart.tsx','utf8');const expression=source.match(/<span>\{(shipping === 0[^\n]+)\}<\/span>/)![1];assert.ok(source.includes('const shipping = shippingEstimate(subtotal)'));assert.ok(source.includes('const totalWithDiscount = finalSubtotal + shipping'));const display=(subtotal:number)=>vm.runInNewContext(expression,{shipping:shippingEstimate(subtotal)});assert.equal(display(11),'€5.00');assert.equal((11-1.10+shippingEstimate(11)).toFixed(2),'14.90');assert.equal(display(199.99),'€5.00');assert.equal(display(200),'Gratuita');assert.equal(display(250),'Gratuita');});
