import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {renderToStaticMarkup} from 'react-dom/server';
import {ProductGrid} from '@/components/product/ProductGrid';

test('Home product section and catalogue/collection listings use the shared mobile grid',()=>{for(const path of ['src/components/home/BestSellersSection.tsx','src/components/CatalogueBrowser.tsx'])assert.match(readFileSync(path,'utf8'),/<ProductGrid/);assert.match(readFileSync('src/pages/Home.tsx','utf8'),/<BestSellersSection/);assert.match(readFileSync('src/pages/Catalog.tsx','utf8'),/<CatalogueBrowser/);assert.match(readFileSync('src/pages/CollectionDetail.tsx','utf8'),/<CatalogueBrowser/);});
test('shared grid retains caller desktop columns and compact mobile spacing',()=>{const html=renderToStaticMarkup(<ProductGrid className="sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"><a href="/product/test">Product</a></ProductGrid>);for(const value of ['grid-cols-2','gap-3','sm:gap-6','lg:grid-cols-3','xl:grid-cols-4','href="/product/test"'])assert.ok(html.includes(value));const css=readFileSync('src/index.css','utf8');assert.match(css,/@media \(max-width: 639px\)/);assert.match(css,/overflow-wrap: anywhere/);assert.match(css,/flex-wrap: wrap/);assert.match(readFileSync('src/components/product/ProductCard.tsx','utf8'),/aspect-square[\s\S]*object-cover/);});
test('responsive columns at requested widths preserve previous tablet and desktop counts',()=>{const catalogue=readFileSync('src/components/CatalogueBrowser.tsx','utf8'),home=readFileSync('src/components/home/BestSellersSection.tsx','utf8');assert.match(catalogue,/sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4/);assert.match(home,/sm:grid-cols-2 lg:grid-cols-4/);for(const width of [320,375,390,430,768,1280]){const columns=(source:string)=>{let count=2;for(const match of source.matchAll(/(sm|lg|xl):grid-cols-(\d+)/g)){const min={sm:640,lg:1024,xl:1280}[match[1] as 'sm'|'lg'|'xl'];if(width>=min)count=Number(match[2]);}return count;};const catalogueColumns=columns(catalogue);const homeColumns=columns(home);assert.equal(catalogueColumns,width===1280?4:2);assert.equal(homeColumns,width===1280?4:2);}});

test('collection previews and loading grid share two mobile columns and retain tablet/desktop layout',()=>{for(const p of ['src/pages/Collections.tsx','src/components/home/CollectionsSection.tsx']){const source=readFileSync(p,'utf8');assert.match(source,/mobileTwoColumnGrid/);assert.match(source,/sm:grid-cols-2 lg:grid-cols-3/);}const card=readFileSync('src/components/CollectionCard.tsx','utf8');assert.match(card,/p-2 sm:p-6/);assert.match(card,/text-sm sm:text-2xl/);assert.match(card,/aspect-\[4\/5\]/);for(const width of [320,375,390,430,768,1280])assert.equal(width>=1024?3:2,width===1280?3:2);});
